/**
 * This class is generated by jOOQ
 */
package ma.jberrich.database;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import ma.jberrich.database.tables.Dept;
import ma.jberrich.database.tables.Emp;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employesdb extends SchemaImpl {

	private static final long serialVersionUID = 2106781413;

	/**
	 * The reference instance of <code>employesdb</code>
	 */
	public static final Employesdb EMPLOYESDB = new Employesdb();

	/**
	 * No further instances allowed
	 */
	private Employesdb() {
		super("employesdb");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Dept.DEPT,
			Emp.EMP);
	}
}
