/**
 * This class is generated by jOOQ
 */
package ma.jberrich.database.tables.records;


import java.math.BigDecimal;

import javax.annotation.Generated;

import ma.jberrich.database.tables.Emp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmpRecord extends UpdatableRecordImpl<EmpRecord> implements Record6<Integer, String, String, Integer, BigDecimal, Integer> {

	private static final long serialVersionUID = -986584655;

	/**
	 * Setter for <code>employesdb.emp.EMPNO</code>.
	 */
	public void setEmpno(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>employesdb.emp.EMPNO</code>.
	 */
	public Integer getEmpno() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>employesdb.emp.ENAME</code>.
	 */
	public void setEname(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>employesdb.emp.ENAME</code>.
	 */
	public String getEname() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>employesdb.emp.JOB</code>.
	 */
	public void setJob(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>employesdb.emp.JOB</code>.
	 */
	public String getJob() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>employesdb.emp.AGE</code>.
	 */
	public void setAge(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>employesdb.emp.AGE</code>.
	 */
	public Integer getAge() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>employesdb.emp.SAL</code>.
	 */
	public void setSal(BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>employesdb.emp.SAL</code>.
	 */
	public BigDecimal getSal() {
		return (BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>employesdb.emp.DEPTNO</code>.
	 */
	public void setDeptno(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>employesdb.emp.DEPTNO</code>.
	 */
	public Integer getDeptno() {
		return (Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String, Integer, BigDecimal, Integer> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String, Integer, BigDecimal, Integer> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Emp.EMP.EMPNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Emp.EMP.ENAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Emp.EMP.JOB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Emp.EMP.AGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<BigDecimal> field5() {
		return Emp.EMP.SAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Emp.EMP.DEPTNO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getEmpno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getEname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getJob();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getAge();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BigDecimal value5() {
		return getSal();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getDeptno();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmpRecord value1(Integer value) {
		setEmpno(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmpRecord value2(String value) {
		setEname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmpRecord value3(String value) {
		setJob(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmpRecord value4(Integer value) {
		setAge(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmpRecord value5(BigDecimal value) {
		setSal(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmpRecord value6(Integer value) {
		setDeptno(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmpRecord values(Integer value1, String value2, String value3, Integer value4, BigDecimal value5, Integer value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EmpRecord
	 */
	public EmpRecord() {
		super(Emp.EMP);
	}

	/**
	 * Create a detached, initialised EmpRecord
	 */
	public EmpRecord(Integer empno, String ename, String job, Integer age, BigDecimal sal, Integer deptno) {
		super(Emp.EMP);

		setValue(0, empno);
		setValue(1, ename);
		setValue(2, job);
		setValue(3, age);
		setValue(4, sal);
		setValue(5, deptno);
	}
}
